//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AtalhoMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AtalhoMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.AtalhoMensagem", typeof(AtalhoMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atalho foi alterado com sucesso..
        /// </summary>
        public static string Atalho_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Atalho_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atalho que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Atalho_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Atalho_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atalho foi cadastrado com sucesso..
        /// </summary>
        public static string Atalho_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Atalho_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui um atalho cadastrado com a URL informada. Informe uma URL diferente para o atalho..
        /// </summary>
        public static string Atalho_Com_Mesma_Url {
            get {
                return ResourceManager.GetString("Atalho_Com_Mesma_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui um atalho cadastrado com o título informado. Informe um título diferente para o atalho..
        /// </summary>
        public static string Atalho_Com_Mesmo_Titulo {
            get {
                return ResourceManager.GetString("Atalho_Com_Mesmo_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atalho encontrado com sucesso..
        /// </summary>
        public static string Atalho_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Atalho_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atalho foi excluído com sucesso..
        /// </summary>
        public static string Atalho_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Atalho_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atalho que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Atalho_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Atalho_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atalho não pertence ao usuário autenticado..
        /// </summary>
        public static string Atalho_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Atalho_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atalho(s) do usuário encontrado(s) com sucesso..
        /// </summary>
        public static string Atalhos_Encontrados_Com_Sucesso {
            get {
                return ResourceManager.GetString("Atalhos_Encontrados_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do atalho informado é inválido..
        /// </summary>
        public static string Id_Atalho_Invalido {
            get {
                return ResourceManager.GetString("Id_Atalho_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O atalho com o ID informado não existe..
        /// </summary>
        public static string Id_Atalho_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Atalho_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID informado é inválido..
        /// </summary>
        public static string Id_Invalido {
            get {
                return ResourceManager.GetString("Id_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do usuário informado é inválido..
        /// </summary>
        public static string Id_Usuario_Invalido {
            get {
                return ResourceManager.GetString("Id_Usuario_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum atalho do usuário foi encontrado..
        /// </summary>
        public static string Nenhum_Atalho_Encontrado {
            get {
                return ResourceManager.GetString("Nenhum_Atalho_Encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título do atalho é obrigatório e não foi informado..
        /// </summary>
        public static string Titulo_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Titulo_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título do atalho deve possuir no máximo 50 caracteres..
        /// </summary>
        public static string Titulo_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Titulo_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL do atalho é obrigatória e não foi informada..
        /// </summary>
        public static string Url_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Url_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL do atalho deve possuir no máximo 3000 caracteres..
        /// </summary>
        public static string Url_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Url_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
    }
}
