//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CartaoCreditoMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CartaoCreditoMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.CartaoCreditoMensagem", typeof(CartaoCreditoMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de crédito alterado com sucesso..
        /// </summary>
        public static string Cartao_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Cartao_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão de crédito que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Cartao_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Cartao_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de crédito cadastrado com sucesso..
        /// </summary>
        public static string Cartao_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Cartao_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui um cartão cadastrado com o nome informado. Informe um nome diferente para o cartão..
        /// </summary>
        public static string Cartao_Com_Mesmo_Nome {
            get {
                return ResourceManager.GetString("Cartao_Com_Mesmo_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de crédito encontrado com sucesso..
        /// </summary>
        public static string Cartao_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Cartao_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de crédito excluído com sucesso..
        /// </summary>
        public static string Cartao_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Cartao_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem outras informações relacionadas a esse cartão de crédito, por isso não é possível excluí-lo..
        /// </summary>
        public static string Cartao_Excluir_Erro_FK {
            get {
                return ResourceManager.GetString("Cartao_Excluir_Erro_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão de crédito que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Cartao_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Cartao_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão de crédito não pertence ao usuário autenticado..
        /// </summary>
        public static string Cartao_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Cartao_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão(ões) do usuário encontrado(s) com sucesso..
        /// </summary>
        public static string Cartoes_Encontrados_Com_Sucesso {
            get {
                return ResourceManager.GetString("Cartoes_Encontrados_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O dia do vencimento da fatura do cartão é inválido..
        /// </summary>
        public static string Dia_Vencimento_Fatura_Invalido {
            get {
                return ResourceManager.GetString("Dia_Vencimento_Fatura_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano da fatura é obrigatório e não foi informado..
        /// </summary>
        public static string Fatura_Ano_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Fatura_Ano_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do pagamento da fatura é obrigatória e não foi informada..
        /// </summary>
        public static string Fatura_Data_Pagamento_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Fatura_Data_Pagamento_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatura foi encontrada com sucesso..
        /// </summary>
        public static string Fatura_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Fatura_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatura não foi encontrada a partir do ID do lançamento informado..
        /// </summary>
        public static string Fatura_Id_Lancamento_Nao_Encontrada {
            get {
                return ResourceManager.GetString("Fatura_Id_Lancamento_Nao_Encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O mês da fatura é obrigatório e não foi informado..
        /// </summary>
        public static string Fatura_Mes_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Fatura_Mes_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pagamento da fatura foi realizado com sucesso..
        /// </summary>
        public static string Fatura_Paga_Com_Sucesso {
            get {
                return ResourceManager.GetString("Fatura_Paga_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O saldo disponível na conta ({0}) é insuficiente para realizar o pagamento da fatura..
        /// </summary>
        public static string Fatura_Saldo_Insuficiente_Pagamento_Fatura {
            get {
                return ResourceManager.GetString("Fatura_Saldo_Insuficiente_Pagamento_Fatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do pagamento é menor que o valor total da fatura. Não é possível realizar o pagamento da fatura nessas condições..
        /// </summary>
        public static string Fatura_Valor_Pagamento_Menor_Valor_Total_Fatura {
            get {
                return ResourceManager.GetString("Fatura_Valor_Pagamento_Menor_Valor_Total_Fatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do cartão de crédito informado é inválido..
        /// </summary>
        public static string Id_Cartao_Invalido {
            get {
                return ResourceManager.GetString("Id_Cartao_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão de crédito com o ID informado não existe..
        /// </summary>
        public static string Id_Cartao_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Cartao_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum cartão do usuário foi encontrado..
        /// </summary>
        public static string Nenhum_Cartao_Encontrado {
            get {
                return ResourceManager.GetString("Nenhum_Cartao_Encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do cartão é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do cartão deve possuir no máximo 100 caracteres..
        /// </summary>
        public static string Nome_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Nome_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação referente ao crédito adicional da fatura deve possuir no máximo 100 caracteres..
        /// </summary>
        public static string Observacao_Credito_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Credito_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação referente ao débito adicional da fatura deve possuir no máximo 100 caracteres..
        /// </summary>
        public static string Observacao_Debito_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Debito_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do limite do cartão é inválido..
        /// </summary>
        public static string Valor_Limite_Invalido {
            get {
                return ResourceManager.GetString("Valor_Limite_Invalido", resourceCulture);
            }
        }
    }
}
