//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoriaMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoriaMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.CategoriaMensagem", typeof(CategoriaMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria alterada com sucesso..
        /// </summary>
        public static string Categoria_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Categoria_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Categoria_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Categoria_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria cadastrada com sucesso..
        /// </summary>
        public static string Categoria_Cadastrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Categoria_Cadastrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui uma categoria cadastrada com o mesmo nome e tipo para a mesma categoria pai..
        /// </summary>
        public static string Categoria_Com_Mesmo_Nome_Tipo {
            get {
                return ResourceManager.GetString("Categoria_Com_Mesmo_Nome_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria encontrada com sucesso..
        /// </summary>
        public static string Categoria_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Categoria_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria excluída com sucesso..
        /// </summary>
        public static string Categoria_Excluida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Categoria_Excluida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem outras informações relacionadas a essa categoria, por isso não é possível excluí-la..
        /// </summary>
        public static string Categoria_Excluir_Erro_FK {
            get {
                return ResourceManager.GetString("Categoria_Excluir_Erro_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Categoria_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Categoria_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria não pertence ao usuário autenticado..
        /// </summary>
        public static string Categoria_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Categoria_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria pai com o ID informado não existe..
        /// </summary>
        public static string Categoria_Pai_Nao_Existe {
            get {
                return ResourceManager.GetString("Categoria_Pai_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria possui categorias filhas. Antes de excluí-la, é preciso excluir primeiramente todas as suas categorias filhas..
        /// </summary>
        public static string Categoria_Pai_Nao_Pode_Ser_Excluida {
            get {
                return ResourceManager.GetString("Categoria_Pai_Nao_Pode_Ser_Excluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria(s) do usuário encontrada(s) com sucesso..
        /// </summary>
        public static string Categorias_Encontradas_Com_Sucesso {
            get {
                return ResourceManager.GetString("Categorias_Encontradas_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da categoria informado é inválido..
        /// </summary>
        public static string Id_Categoria_Invalido {
            get {
                return ResourceManager.GetString("Id_Categoria_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria com o ID informado não existe..
        /// </summary>
        public static string Id_Categoria_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Categoria_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da categoria pai não pode ser igual ao ID da categoria..
        /// </summary>
        public static string Id_Categoria_Pai_Id_Categoria_Nao_Podem_Ser_Iguais {
            get {
                return ResourceManager.GetString("Id_Categoria_Pai_Id_Categoria_Nao_Podem_Ser_Iguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da categoria pai informado é inválido..
        /// </summary>
        public static string Id_Categoria_Pai_Invalido {
            get {
                return ResourceManager.GetString("Id_Categoria_Pai_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma categoria do usuário foi encontrado..
        /// </summary>
        public static string Nenhuma_categoria_encontrada {
            get {
                return ResourceManager.GetString("Nenhuma_categoria_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da categoria é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da categoria deve possuir no máximo 100 caracteres..
        /// </summary>
        public static string Nome_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Nome_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da categoria informado é inválido..
        /// </summary>
        public static string Tipo_Invalido {
            get {
                return ResourceManager.GetString("Tipo_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da categoria informado não pode ser diferente do tipo da categoria pai..
        /// </summary>
        public static string Tipo_Nao_Pode_Ser_Diferente_Tipo_Categoria_Pai {
            get {
                return ResourceManager.GetString("Tipo_Nao_Pode_Ser_Diferente_Tipo_Categoria_Pai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da categoria  é obrigatório e não foi informado..
        /// </summary>
        public static string Tipo_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Tipo_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
    }
}
