//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContaMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContaMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.ContaMensagem", typeof(ContaMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise da carteira de ações obtida com sucesso..
        /// </summary>
        public static string Analise_Carteira_Acoes_Obtida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Analise_Carteira_Acoes_Obtida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise da carteira da ação obtida com sucesso..
        /// </summary>
        public static string Analise_Carteira_Obtida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Analise_Carteira_Obtida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A análise da carteira só é possível para contas do tipo renda variável..
        /// </summary>
        public static string Analise_Carteira_Somente_Conta_Renda_Variavel {
            get {
                return ResourceManager.GetString("Analise_Carteira_Somente_Conta_Renda_Variavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta alterada com sucesso..
        /// </summary>
        public static string Conta_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Conta_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Conta_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Conta_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta cadastrada com sucesso..
        /// </summary>
        public static string Conta_Cadastrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Conta_Cadastrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui uma conta cadastrada com o nome informado. Informe um nome diferente para a conta..
        /// </summary>
        public static string Conta_Com_Mesmo_Nome {
            get {
                return ResourceManager.GetString("Conta_Com_Mesmo_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta de destino da transferência, com o ID informado não existe..
        /// </summary>
        public static string Conta_Destino_Transferencia_Nao_Existe {
            get {
                return ResourceManager.GetString("Conta_Destino_Transferencia_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta de destino da transferência não pertence ao usuário autenticado..
        /// </summary>
        public static string Conta_Destino_Transferencia_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Conta_Destino_Transferencia_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta encontrada com sucesso..
        /// </summary>
        public static string Conta_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Conta_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta excluída com sucesso..
        /// </summary>
        public static string Conta_Excluida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Conta_Excluida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem outras informações relacionadas a essa conta, por isso não é possível excluí-la..
        /// </summary>
        public static string Conta_Excluir_Erro_FK {
            get {
                return ResourceManager.GetString("Conta_Excluir_Erro_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Conta_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Conta_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta não pertence ao usuário autenticado..
        /// </summary>
        public static string Conta_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Conta_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta de origem da transferência, com o ID informado não existe..
        /// </summary>
        public static string Conta_Origem_Transferencia_Nao_Existe {
            get {
                return ResourceManager.GetString("Conta_Origem_Transferencia_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta de origem da transferência não pertence ao usuário autenticado..
        /// </summary>
        public static string Conta_Origem_Transferencia_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Conta_Origem_Transferencia_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta(s) do usuário encontrada(s) com sucesso..
        /// </summary>
        public static string Contas_Encontradas_Com_Sucesso {
            get {
                return ResourceManager.GetString("Contas_Encontradas_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data da transfêrencia é inválida..
        /// </summary>
        public static string Data_Transferencia_Invalida {
            get {
                return ResourceManager.GetString("Data_Transferencia_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta de destino da transferência é inválido..
        /// </summary>
        public static string Id_Conta_Destino_Transferencia_Invalido {
            get {
                return ResourceManager.GetString("Id_Conta_Destino_Transferencia_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta informado é inválido..
        /// </summary>
        public static string Id_Conta_Invalido {
            get {
                return ResourceManager.GetString("Id_Conta_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta com o ID informado não existe..
        /// </summary>
        public static string Id_Conta_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Conta_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta não foi informado..
        /// </summary>
        public static string Id_Conta_Nao_Informado {
            get {
                return ResourceManager.GetString("Id_Conta_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da conta de origem da transferência é inválido..
        /// </summary>
        public static string Id_Conta_Origem_Transferencia_Invalido {
            get {
                return ResourceManager.GetString("Id_Conta_Origem_Transferencia_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma conta do usuário foi encontrada..
        /// </summary>
        public static string Nenhuma_Conta_Encontrada {
            get {
                return ResourceManager.GetString("Nenhuma_Conta_Encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da instituição da conta deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Nome_Instituicao_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Nome_Instituicao_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da conta é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da conta deve possuir no máximo 100 caracteres..
        /// </summary>
        public static string Nome_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Nome_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da agência da conta deve possuir no máximo 20 caracteres..
        /// </summary>
        public static string Numero_Agencia_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Numero_Agencia_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número da conta deve possuir no máximo 20 caracteres..
        /// </summary>
        public static string Numero_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Numero_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação da transferência deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Observacao_Transferencia_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Transferencia_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O saldo disponível da conta origem ({0}) é insuficiente..
        /// </summary>
        public static string Saldo_Insuficiente_Conta_Origem_Transferencia {
            get {
                return ResourceManager.GetString("Saldo_Insuficiente_Conta_Origem_Transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da conta é inválido ou não foi informado..
        /// </summary>
        public static string Tipo_Invalido_Ou_Nao_Informado {
            get {
                return ResourceManager.GetString("Tipo_Invalido_Ou_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transferência foi realizada com sucesso..
        /// </summary>
        public static string Transferencia_Realizada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Transferencia_Realizada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do transferência é inválido..
        /// </summary>
        public static string Valor_Transferencia_Invalido {
            get {
                return ResourceManager.GetString("Valor_Transferencia_Invalido", resourceCulture);
            }
        }
    }
}
