//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LancamentoMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LancamentoMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.LancamentoMensagem", typeof(LancamentoMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do lançamento não pode ser superior a data atual..
        /// </summary>
        public static string Data_Lancamento_Maior_Data_Corrente {
            get {
                return ResourceManager.GetString("Data_Lancamento_Maior_Data_Corrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do lançamento informado é inválido..
        /// </summary>
        public static string Id_Lancamento_Invalido {
            get {
                return ResourceManager.GetString("Id_Lancamento_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O lançamento com o ID informado não existe..
        /// </summary>
        public static string Id_Lancamento_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Lancamento_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento alterado com sucesso..
        /// </summary>
        public static string Lancamento_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Lancamento_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O lançamento que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Lancamento_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Lancamento_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento cadastrado com sucesso..
        /// </summary>
        public static string Lancamento_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Lancamento_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento encontrado com sucesso..
        /// </summary>
        public static string Lancamento_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Lancamento_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento excluído com sucesso..
        /// </summary>
        public static string Lancamento_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Lancamento_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O lançamento que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Lancamento_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Lancamento_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O lançamento não pertence ao usuário autenticado..
        /// </summary>
        public static string Lancamento_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Lancamento_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período informado para é inválido. Verifique as datas informadas..
        /// </summary>
        public static string Lancamento_Procurar_Periodo_Invalido {
            get {
                return ResourceManager.GetString("Lancamento_Procurar_Periodo_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento(s) do usuário encontrado(s) com sucesso..
        /// </summary>
        public static string Lancamentos_Encontrados_Com_Sucesso {
            get {
                return ResourceManager.GetString("Lancamentos_Encontrados_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum lançamento do usuário foi encontrado..
        /// </summary>
        public static string Nenhuma_lancamento_encontrado {
            get {
                return ResourceManager.GetString("Nenhuma_lancamento_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação do lançamento deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Observacao_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de ações informada para venda é maior que a quantidade de ações disponíveis na carteira..
        /// </summary>
        public static string Qtd_Acoes_Venda_Maior_Disponivel_Carteira {
            get {
                return ResourceManager.GetString("Qtd_Acoes_Venda_Maior_Disponivel_Carteira", resourceCulture);
            }
        }
    }
}
