//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LancamentoDetalheMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LancamentoDetalheMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.LancamentoDetalheMensagem", typeof(LancamentoDetalheMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhe cadastrado com sucesso..
        /// </summary>
        public static string Detalhe_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Detalhe_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhe excluído com sucesso..
        /// </summary>
        public static string Detalhe_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Detalhe_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O detalhe que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Detalhe_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Detalhe_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria do detalhe e do lançamento não podem ser iguais..
        /// </summary>
        public static string Id_Categoria_Igual_Categoria_Lancamento {
            get {
                return ResourceManager.GetString("Id_Categoria_Igual_Categoria_Lancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da categoria é obrigatório e não foi informado..
        /// </summary>
        public static string Id_Categoria_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Id_Categoria_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do detalhe informado é inválido..
        /// </summary>
        public static string Id_Detalhe_Invalido {
            get {
                return ResourceManager.GetString("Id_Detalhe_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O detalhe com o ID informado não existe..
        /// </summary>
        public static string Id_Detalhe_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Detalhe_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A observação do detalhe deve possuir no máximo 500 caracteres..
        /// </summary>
        public static string Observacao_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Observacao_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma dos valores dos detalhes é maior que o valor informado para o lançamento..
        /// </summary>
        public static string Soma_Detalhes_Mais_Valor_Detalhe_Maior_Valor_Lancamento {
            get {
                return ResourceManager.GetString("Soma_Detalhes_Mais_Valor_Detalhe_Maior_Valor_Lancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do detalhe é igual ou maior que o valor informado para o lançamento. Informe um valor menor que o valor do lançamento..
        /// </summary>
        public static string Valor_Detalhe_Maior_Ou_Igual_Valor_Lancamento {
            get {
                return ResourceManager.GetString("Valor_Detalhe_Maior_Ou_Igual_Valor_Lancamento", resourceCulture);
            }
        }
    }
}
