//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LancamentoAnexoMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LancamentoAnexoMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.LancamentoAnexoMensagem", typeof(LancamentoAnexoMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo cadastrado com sucesso..
        /// </summary>
        public static string Anexo_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Anexo_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O anexo que se deseja fazer o download, não pertence ao usuário autenticado..
        /// </summary>
        public static string Anexo_Download_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Anexo_Download_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O anexo foi encontrado com sucesso..
        /// </summary>
        public static string Anexo_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Anexo_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo excluído com sucesso..
        /// </summary>
        public static string Anexo_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Anexo_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O anexo que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Anexo_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Anexo_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O conteúdo do arquivo do anexo não foi informado..
        /// </summary>
        public static string Arquivo_Conteudo_Nao_Informado {
            get {
                return ResourceManager.GetString("Arquivo_Conteudo_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do arquivo informado ({0} Mb) é superior ao limite máximo permitido de 5 Mb..
        /// </summary>
        public static string Arquivo_Tamanho_Nao_Permitido {
            get {
                return ResourceManager.GetString("Arquivo_Tamanho_Nao_Permitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do anexo é obrigatória e não foi informada..
        /// </summary>
        public static string Descricao_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Descricao_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do anexo deve possuir no máximo 200 caracteres..
        /// </summary>
        public static string Descricao_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Descricao_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do anexo informado é inválido..
        /// </summary>
        public static string Id_Anexo_Invalido {
            get {
                return ResourceManager.GetString("Id_Anexo_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O anexo com o ID informado não existe..
        /// </summary>
        public static string Id_Anexo_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Anexo_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um arquivo armazenado com o mesmo nome, na pasta do ano/mês do lançamento no Google Drive..
        /// </summary>
        public static string Nome_Arquivo_Ja_Existe_Google_Drive {
            get {
                return ResourceManager.GetString("Nome_Arquivo_Ja_Existe_Google_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do arquivo do anexo é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Arquivo_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Arquivo_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do arquivo do anexo deve possuir no máximo 50 caracteres..
        /// </summary>
        public static string Nome_Arquivo_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Nome_Arquivo_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
    }
}
