//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeriodoMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodoMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.PeriodoMensagem", typeof(PeriodoMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data fim do período é obrigatória e não foi informada..
        /// </summary>
        public static string Data_Fim_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Data_Fim_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data início do período é obrigatória e não foi informada..
        /// </summary>
        public static string Data_Inicio_Obrigatoria_Nao_Informada {
            get {
                return ResourceManager.GetString("Data_Inicio_Obrigatoria_Nao_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data início do período é maior ou igual a data fim..
        /// </summary>
        public static string Data_Periodo_Invalidas {
            get {
                return ResourceManager.GetString("Data_Periodo_Invalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhum período que compreenda a data informada..
        /// </summary>
        public static string Data_Periodo_Nao_Existe {
            get {
                return ResourceManager.GetString("Data_Periodo_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As datas informadas pelo período, já são abrangidas por outro período..
        /// </summary>
        public static string Datas_Abrangidas_Outro_Periodo {
            get {
                return ResourceManager.GetString("Datas_Abrangidas_Outro_Periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do período informado é inválido..
        /// </summary>
        public static string Id_Periodo_Invalido {
            get {
                return ResourceManager.GetString("Id_Periodo_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período com o ID informado não existe..
        /// </summary>
        public static string Id_Periodo_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Periodo_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum período do usuário foi encontrado..
        /// </summary>
        public static string Nenhum_periodo_encontrado {
            get {
                return ResourceManager.GetString("Nenhum_periodo_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do período é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve possuir no máximo 50 caracteres..
        /// </summary>
        public static string Nome_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Nome_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui um período cadastrado que abrange as datas informadas..
        /// </summary>
        public static string Periodo_Abrange_Datas_Informadas {
            get {
                return ResourceManager.GetString("Periodo_Abrange_Datas_Informadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período alterado com sucesso..
        /// </summary>
        public static string Periodo_Alterado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Periodo_Alterado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Periodo_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Periodo_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período cadastrado com sucesso..
        /// </summary>
        public static string Periodo_Cadastrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Periodo_Cadastrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período encontrado com sucesso..
        /// </summary>
        public static string Periodo_Encontrado_Com_Sucesso {
            get {
                return ResourceManager.GetString("Periodo_Encontrado_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período excluído com sucesso..
        /// </summary>
        public static string Periodo_Excluido_Com_Sucesso {
            get {
                return ResourceManager.GetString("Periodo_Excluido_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Periodo_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Periodo_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período não pertence ao usuário autenticado..
        /// </summary>
        public static string Periodo_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Periodo_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data informada é inválida. Informe uma data superior á {0}..
        /// </summary>
        public static string Periodo_Procura_Data_Invalida {
            get {
                return ResourceManager.GetString("Periodo_Procura_Data_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período(s) do usuário encontrado(s) com sucesso..
        /// </summary>
        public static string Periodos_Encontrados_Com_Sucesso {
            get {
                return ResourceManager.GetString("Periodos_Encontrados_Com_Sucesso", resourceCulture);
            }
        }
    }
}
