//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JNogueira.Bufunfa.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PessoaMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PessoaMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JNogueira.Bufunfa.Dominio.Resources.PessoaMensagem", typeof(PessoaMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da pessoa informado é inválido..
        /// </summary>
        public static string Id_Pessoa_Invalido {
            get {
                return ResourceManager.GetString("Id_Pessoa_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pessoa com o ID informado não existe..
        /// </summary>
        public static string Id_Pessoa_Nao_Existe {
            get {
                return ResourceManager.GetString("Id_Pessoa_Nao_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma pessoa do usuário foi encontrado..
        /// </summary>
        public static string Nenhuma_pessoa_encontrada {
            get {
                return ResourceManager.GetString("Nenhuma_pessoa_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da pessoa é obrigatório e não foi informado..
        /// </summary>
        public static string Nome_Obrigatorio_Nao_Informado {
            get {
                return ResourceManager.GetString("Nome_Obrigatorio_Nao_Informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da pessoa deve possuir no máximo 200 caracteres..
        /// </summary>
        public static string Nome_Tamanho_Maximo_Excedido {
            get {
                return ResourceManager.GetString("Nome_Tamanho_Maximo_Excedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa alterada com sucesso..
        /// </summary>
        public static string Pessoa_Alterada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Pessoa_Alterada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pessoa que se deseja alterar, não pertence ao usuário autenticado..
        /// </summary>
        public static string Pessoa_Alterar_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Pessoa_Alterar_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa cadastrada com sucesso..
        /// </summary>
        public static string Pessoa_Cadastrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Pessoa_Cadastrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já possui uma pessoa cadastrada com o nome informado. Informe um nome diferente para a pessoa..
        /// </summary>
        public static string Pessoa_Com_Mesmo_Nome {
            get {
                return ResourceManager.GetString("Pessoa_Com_Mesmo_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa encontrada com sucesso..
        /// </summary>
        public static string Pessoa_Encontrada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Pessoa_Encontrada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa excluída com sucesso..
        /// </summary>
        public static string Pessoa_Excluida_Com_Sucesso {
            get {
                return ResourceManager.GetString("Pessoa_Excluida_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pessoa que se deseja excluir, não pertence ao usuário autenticado..
        /// </summary>
        public static string Pessoa_Excluir_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Pessoa_Excluir_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pessoa não pertence ao usuário autenticado..
        /// </summary>
        public static string Pessoa_Nao_Pertence_Usuario {
            get {
                return ResourceManager.GetString("Pessoa_Nao_Pertence_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa(s) do usuário encontrada(s) com sucesso..
        /// </summary>
        public static string Pessoas_Encontradas_Com_Sucesso {
            get {
                return ResourceManager.GetString("Pessoas_Encontradas_Com_Sucesso", resourceCulture);
            }
        }
    }
}
