# Define a imagem do SDK
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build-env

# Cria o diretório src e copiando todo o código-fonte para ele
WORKDIR /src
COPY . ./

# Acessa o diretório do frontend, publicando para o diretório "publish"
WORKDIR /src/bufunfa-web
RUN dotnet publish -c Release -o publish

# Define a imagem do runtime
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

WORKDIR /app

# Copia todos os publicáveis para o diretório app
COPY --from=build-env /src/bufunfa-web/publish .

RUN rm appsettings.Development.json
RUN rm bundleconfig.json
RUN rm -rf publish
RUN rm -rf cs
RUN rm -rf de
RUN rm -rf es
RUN rm -rf fr
RUN rm -rf it
RUN rm -rf ja
RUN rm -rf ko
RUN rm -rf pl
RUN rm -rf ru
RUN rm -rf tr
RUN rm -rf zh-*

# Install cultures (same approach as Alpine SDK image)
RUN apk add --no-cache icu-libs

# Disable the invariant mode (set in base image)
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# Define o environment
ENV ASPNETCORE_ENVIRONMENT=Docker

ENTRYPOINT ["dotnet", "bufunfa-web.dll"]