# Define a imagem do SDK
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build-env

# Cria o diretório src e copiando todo o código-fonte para ele
WORKDIR /src
COPY . ./

# Acessa o diretório da API, publicando para o diretório "publish"
WORKDIR /src/bufunfa-api
RUN dotnet publish -c Release -o publish

# Define a imagem do runtime
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

RUN ["apt-get", "update"]
# Adicionando bibliotecas para a cultura PT-BR
RUN apt-get install -y locales
RUN sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

WORKDIR /app

# Copia todos os publicáveis para o diretório app
COPY --from=build-env /src/bufunfa-api/publish .

# Define o environment
ENV ASPNETCORE_ENVIRONMENT=Production

ENV TZ=America/Sao_Paulo
ENV LANG pt_BR.UTF-8
ENV LANGUAGE ${LANG}
ENV LC_ALL ${LANG}

ENTRYPOINT ["dotnet", "bufunfa-api.dll"]