version: '3'
services:
  dbServer:
    image: mysql:5.7
    container_name: bufunfa_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Suf1st@"
      MYSQL_DATABASE: "bufunfa_db"
      MYSQL_USER: "bufunfa"
      MYSQL_PASSWORD: "bufunfa"
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ../_mysql:/var/lib/mysql
    networks:
      - bufufnfa-network

networks: 
  bufufnfa-network:
    driver: bridge